# Build stage
FROM golang:1.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main

# Final stage
FROM public.ecr.aws/lambda/provided:al2

WORKDIR /var/task

COPY --from=builder /app/main .
COPY data ./data/

CMD ["main"]